//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP_Bashlykova523
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public string Reason { get; set; }
        public int StatusID { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual ComplaintStatus ComplaintStatus { get; set; }
        public virtual User User { get; set; }
    }
}
